version: '2'

services:
  chillpatrickdotcom:
    image: nginx:latest
    restart: always
    networks:
      - nginxbridge
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./chill.svg.html:/usr/share/nginx/html/chill.svg
      - ./bg.jpg:/usr/share/nginx/html/bg.jpg
    container_name: chillpatrickdotcom
    labels:
      - "traefik.docker.network=nginxbridge"
      - "traefik.enable=true"
      - "traefik.http.routers.chillpatrickdotcom.rule=Host(`chillpatrick.com`)"
      - "traefik.http.routers.chillpatrickdotcom.tls=true"
      - "traefik.http.routers.chillpatrickdotcom.tls.certresolver=myresolver"
      - "traefik.port=80"

networks:
  nginxbridge:
    external: true